### PR TITLE
Updated StackExchange.Redis library version

### PR DESCRIPTION
**Pull request by borgmatthew**

### CODE REVIEW

**Comment by MichaCo** [comment]
Hi @borgmatthew ,
thanks for the PR

Why did you make the changes in `RedisValueConverter`?

**Comment by borgmatthew** [comment]
@MichaCo the changes in `RedisValueConverter` were required for the project to compile. Casting was required as the references were ambiguous. I am attempting to update to the latest Redis client version, which is 2.2.4.

**Comment by borgmatthew** [comment]
@MichaCo Updated to the latest version of the StackExchange.Redis library

**Comment by MichaCo** [comment]
Could you undo the icon thing and any changes to the test project?
`<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />`

I actually just did similar changes, but I can merge your. Just for those 2 thing I got more/different updates.

**Comment by borgmatthew** [comment]
@MichaCo No worries, this can be closed then. Please note that there is a newer version of StackExchange.Redis, which is version **2.2.62**

**Comment by MichaCo** [comment]
ok

**Pull request closed without merging**
